# Generated by Django 4.1.7 on 2023-03-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std', '0002_rename_person_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pan',
            field=models.FileField(default='abc', upload_to='static/', verbose_name='pan'),
        ),
    ]
